theme: minima
title: Erick Jara Portfolio
author: Erick Jara
email: erick_jara@alumni.brown.edu
description: > # this means to ignore newlines until "baseurl:"
 This page is to showcase my resume and portfolio.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  efjara # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
